sonar.projectKey=sw5005-sus_ceramicraft-log-mservice
sonar.organization=sw5005-sus

# sonar.projectName=ceramicraft-log-mservice
# sonar.projectVersion=1.0

sonar.sources=src/ceramicraft_log_mservice
sonar.tests=tests
sonar.exclusions=src/ceramicraft_log_mservice/pb/**
sonar.test.exclusions=**/pb/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
