# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audit_log.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audit_log.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61udit_log.proto\x12\x0f\x63\x65ramicraft.log\"c\n\x15RecordAuditLogRequest\x12\x10\n\x08\x61\x63tor_id\x18\x01 \x01(\x03\x12#\n\x04role\x18\x02 \x01(\x0e\x32\x15.ceramicraft.log.Role\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\";\n\x16RecordAuditLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\t*D\n\x04Role\x12\x14\n\x10ROLE_UNSPECIFIED\x10\x00\x12\x0c\n\x08MERCHANT\x10\x01\x12\x0c\n\x08\x43USTOMER\x10\x02\x12\n\n\x06SYSTEM\x10\x03\x32t\n\x0f\x41uditLogService\x12\x61\n\x0eRecordAuditLog\x12&.ceramicraft.log.RecordAuditLogRequest\x1a\'.ceramicraft.log.RecordAuditLogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audit_log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROLE']._serialized_start=198
  _globals['_ROLE']._serialized_end=266
  _globals['_RECORDAUDITLOGREQUEST']._serialized_start=36
  _globals['_RECORDAUDITLOGREQUEST']._serialized_end=135
  _globals['_RECORDAUDITLOGRESPONSE']._serialized_start=137
  _globals['_RECORDAUDITLOGRESPONSE']._serialized_end=196
  _globals['_AUDITLOGSERVICE']._serialized_start=268
  _globals['_AUDITLOGSERVICE']._serialized_end=384
# @@protoc_insertion_point(module_scope)
